apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: appmesh-eks
  region: us-east-1

nodeGroups:
  - name: ng-1
    instanceType: m5.large
    desiredCapacity: 3
    minSize: 2
    maxSize: 4
    privateNetworking: false
    ssh:
      allow: true
    iam:
      withAddonPolicies:
        autoScaler: true
        appMesh: true
        ALBIngress: true
        ebs: true
